#!/usr/bin/env bash

export DEPENDENCIES="lib/jasmin.jar"
JAVA="java"
export LANG="jvm"
export VM_BINARIES="$JAVA"

source usage.sh

OUTPUT=${SOURCE%.ins}.j
OUTPUT_DIR=$(dirname "$OUTPUT")

"$COMPILER" "$LANG" "$SOURCE" > "$OUTPUT"
"$JAVA" -cp "$DEPENDENCY" jasmin.Main -d "$OUTPUT_DIR" "$OUTPUT" > /dev/null
