#!/usr/bin/env bash

export DEPENDENCIES=""
export LANG="llvm"
LLVM_AS="llvm-as"
export VM_BINARIES="$LLVM_AS $LLVM_LINK"

source usage.sh

OUTPUT=${SOURCE%.ins}.ll
BYTECODE=${SOURCE%.ins}.bc

"$COMPILER" "$LANG" "$SOURCE" > "$OUTPUT"
"$LLVM_AS" "$OUTPUT" -o "$BYTECODE"
